application: spritsit
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: "latest"

handlers:
- url: /read
  static_files: lib/static/index.html
  upload: lib/static/index\.html

- url: /assets
  static_dir: lib/static/

- url: /.*
  script: spritsit.application

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.cmd$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.sass$
- ^(.*/)?.*\.jade$

env_variables:
  READ_API_TOKEN: '112358'
