application: spritsit
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: "latest"

handlers:
- url: /read
  static_files: lib/codepen/index.html
  upload: lib/codepen/index\.html

- url: /assets
  static_dir: lib/codepen/

- url: /.*
  script: spritsit.application

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.sass$
- ^(.*/)?.*\.jade$

env_variables:
  DJANGO_SETTINGS_MODULE: 'webapp.settings'
