application: spritsit
version: 0-2-alpha
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: latest

- name: jinja2
  version: latest

- name: markupsafe
  version: latest

handlers:
- url: /assets/css/(.*ttf)
  static_files: static/css/\1
  upload: static/css/(.*\.ttf)
  mime_type: application/x-font-truetype

- url: /assets/css/(.*svg)
  static_files: static/css/\1
  upload: static/css/(.*\.svg)
  mime_type: image/svg+xml

- url: /assets/css/(.*woff)
  static_files: static/css/\1
  upload: static/css/(.*\.woff)
  mime_type: application/font-woff

- url: /assets/css/(.*eot)
  static_files: static/css/\1
  upload: static/css/(.*\.eot)
  mime_type: application/vng.ms-fontobject

- url: /assets
  static_dir: static/

- url: /.*
  script: spritsit.app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.cmd$
- ^(.*/)?.*\.sass$
- ^(.*/)?.*\.jade$

env_variables:
  ALLOW_STREAMING: false

inbound_services:
- warmup


